---

ansible_connection: local

openshift_cluster_content:
- galaxy_requirements: "{{ playbook_dir }}/galaxy_requirements.yml"
- object: ci-cd-builds
  content:
  - name: jenkins-s2i
    template: "{{ playbook_dir }}/openshift-templates/jenkins-s2i-build/template.yml"
    params: "{{ playbook_dir }}/params/jenkins/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins
  - name: sonarqube
    template: "{{ playbook_dir }}/openshift-templates/docker-build/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/build"
    namespace: "{{ ci_cd_namespace }}"
    tags:
      - sonarqube     
- object: jenkins-slave-nodes
  content:
  - name: jenkins-slave-mvn
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/mvn"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins-slaves
    - mvn-slave
  - name: jenkins-slave-npm
    template: "https://raw.githubusercontent.com/redhat-cop/containers-quickstarts/v1.3/jenkins-slaves/templates/jenkins-slave-generic-template.yml"
    params: "{{ playbook_dir }}/params/jenkins-slaves/npm"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins-slaves
    - npm-slave
- object: ci-cd-deployments
  content:
  - name: sonarqube
    template: "{{ playbook_dir }}/openshift-templates/sonarqube/template.yml"
    params: "{{ playbook_dir }}/params/sonarqube/deploy"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - sonarqube
  - name: sonarqube-postgresql
    template: "openshift//postgresql-persistent"
    params: "{{ playbook_dir }}/params/sonarqube/postgresql"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - sonarqube
  - name: jenkins-persistent
    template: "{{ playbook_dir }}/openshift-templates/jenkins/jenkins-persistent-template.yml"
    params: "{{ playbook_dir }}/params/jenkins/deploy"
    namespace: "{{ ci_cd_namespace }}"
    tags:
    - jenkins
