---

ansible_connection: local

openshift_cluster_content:
- object: projectrequest
  content:
  - name: ci-cd
    template: "{{ playbook_dir }}/openshift-templates/project-request/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/ci-cd"
    tags:
    - projects
  - name: dev
    template: "{{ playbook_dir }}/openshift-templates/project-request/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/dev"
    tags:
    - projects
  - name: demo
    template: "{{ playbook_dir }}/openshift-templates/project-request/template.yml"
    action: create
    params: "{{ playbook_dir }}/params/projectrequests/test"
    tags:
    - projects
- object: group-role-binding
  content:
  - name: "ci-cd-acl"
    namespace: "{{ ci_cd_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl"
    namespace: "{{ dev_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
  - name: "labs-dev-acl"
    namespace: "{{ test_namespace }}"
    template: "{{ playbook_dir }}/openshift-templates/rolebinding-group/template.yml"
    params: "{{ playbook_dir }}/params/rolebinding-group/all"
    tags:
    - rolebinding-group
